### ISSUE TITLE
clone GitBook style

### ISSUE THREAD

**Issue by cclypeatus** [dndworld/dndworld.github.io#8]
# Quick Links

- GitBook version: https://dndworldtest.gitbook.io/dw-guide
- Retype documentation: https://retype.com/

# TODO

- [x] crop banner size to be more strip like
- [x] `blockquote` text `color` should be more light gray
- [x] make font size smaller (currently looks bad on mobile)

**Comment by cclypeatus** [comment]
i can get the banner to span from left to right edge too, but that will call for some delving into responsive design first so putting it off
